### ISSUE TITLE
چطور سایدبار رو به صفحه ی درباره ی ما اضافه کنیم؟

### ISSUE THREAD

**Issue by Mahdi-Hazrati** [srezasm/minimal-mistakes-rtl#1]
سلام من از نسخه تغییر داده شده شما استفاده میکنم ولی دو تا باگ مهم داره!
ساید بار در درباره ما نمایش داده نمیشه!
فونت کلمات انگلیسی درست نمایش داده نمیشه!
لطفا راهنمایی کنید چطور درستش کنم

**Comment by srezasm** [comment]
باسپاس از توجهتون.
لطفاً جزئیات بیشتری به همراه عکس بارگزاری کنید تا در اسرع وقت تصحیح کنم.

**Comment by srezasm** [comment]
فونت متون انگلیسی در نسخهٔ نمایشی به آدرس
https://srezasm.github.io/minimal-mistakes-rtl/article/first-farsi-post/
مشکلی نداره.

**Comment by srezasm** [comment]
مشکل سایدبار هم حل شد.

**Comment by Mahdi-Hazrati** [comment]
چند تا باگ مهم اگر اصلاح بشه قالب استیبل میشه و میشه براحتی استفاده کرد.
 در تمام صفحات ساید بار اطلاعات کاربر همانند نسخه اصلی قالب نمایش داده بشه!
 اعداد نمایش داده شده فارسی بشه
 در کلمات انگلیسی فونت بصورت صحیح اعمال بشه (حد الامکان فونت وزیر)
 تایتل های مقالات در صفحه پست ها با فونت ساحل نمایش داده بشه
 تکست های وبسایت با فونت وزیر و تمام اطلاعات مقالات با فونت ساحل نمایش داده بشه

**Comment by Mahdi-Hazrati** [comment]
و لطفا راهنمایی کنید چطور در لوکال ران پروژه رو ران کنم من اولین باره از jekyll استفاده میکنم و با ساز و کارش آشنا نیستم

**Comment by srezasm** [comment]
علی‌رغم اینکه با حرفاتون موافقم اما بدلیل مشغله زیاد درحال حاضر نمی‌تونم تغییرات مذکور رو اعمال کنم. ممنون میشم اگر شما اعمالشون کنید و pull request بزنید.

> چند تا باگ مهم اگر اصلاح بشه قالب استیبل میشه و میشه براحتی استفاده کرد. در تمام صفحات ساید بار اطلاعات کاربر همانند نسخه اصلی قالب نمایش داده بشه! اعداد نمایش داده شده فارسی بشه در کلمات انگلیسی فونت بصورت صحیح اعمال بشه (حد الامکان فونت وزیر) تایتل های مقالات در صفحه پست ها با فونت ساحل نمایش داده بشه تکست های وبسایت با فونت وزیر و تمام اطلاعات مقالات با فونت ساحل نمایش داده بشه

**Comment by srezasm** [comment]
> و لطفا راهنمایی کنید چطور در لوکال ران پروژه رو ران کنم من اولین باره از jekyll استفاده میکنم و با ساز و کارش آشنا نیستم

برای نصب، طبق داکیومنتش پیش برید:
https://jekyllrb.com/docs/installation

برای آشنایی با سازوکار این قالب هم می‌تونید به داکیومنت ها و نحوهٔ پیاده سازی نسخهٔ اصلیش مراجعه کنید:
https://mmistakes.github.io/minimal-mistakes

درکل پیچیدگی خاصی نداره اگر با طراحی سایت و قالب markdown آشنایی داشته باشید، به راحتی می‌تونید ویرایشش کنید.

**Comment by Mahdi-Hazrati** [comment]
من با طراحی وب آشنایی دارم فقط در حال حاضر دارم سعی میکنم سازکار قالب رو درک کنم اگر تونستم در لوکال ران کنم حتما باگ رو فیکس میکنم و PR میزنم
ممنون که باگ ها رو فیکس کردی :)

**Comment by srezasm** [comment]
خواهش میکنم. کمی استمرار بورزید، یک روزه از برش میشید ;)
